# Generated by Django 2.1.7 on 2020-11-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='example1',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='示例1'),
        ),
        migrations.AddField(
            model_name='question',
            name='example2',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='示例2'),
        ),
        migrations.AddField(
            model_name='question',
            name='example3',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='示例3'),
        ),
        migrations.AddField(
            model_name='question',
            name='example4',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='示例4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='问题'),
        ),
    ]
