# Generated by Django 2.1.7 on 2020-11-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0004_auto_20201107_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.TextField(blank=True, null=True, verbose_name='正确答案'),
        ),
    ]
