# Generated by Django 2.1.7 on 2020-11-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0005_auto_20201107_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
