# Generated by Django 2.1.7 on 2020-11-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0006_question_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
