# Generated by Django 2.1.7 on 2020-11-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0007_auto_20201116_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='作者'),
        ),
    ]
