# Generated by Django 2.1.7 on 2020-11-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0010_auto_20201116_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='问题'),
        ),
    ]
