# Generated by Django 2.1.7 on 2020-11-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0011_auto_20201117_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='display',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
    ]
