# Generated by Django 2.1.7 on 2020-11-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0012_auto_20201117_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='functionname',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='函数名'),
        ),
        migrations.AlterField(
            model_name='question',
            name='display',
            field=models.BooleanField(default=True, verbose_name='是否展示此题'),
        ),
    ]
