# Generated by Django 2.1.7 on 2020-11-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0013_auto_20201117_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='functionname',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='函数名'),
        ),
    ]
