# Generated by Django 2.1.7 on 2020-11-18 11:09

from django.db import migrations, models
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0014_auto_20201117_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.CharField(max_length=1000, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=None, to='oj.Category', verbose_name='题型'),
        ),
        migrations.AlterField(
            model_name='question',
            name='example1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='示例1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='example2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='示例2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='example3',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='示例3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='example4',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='示例4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='functionname',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='初始代码'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='选项一'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='选项二'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='选项三'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='选项四'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=simditor.fields.RichTextField(verbose_name='问题'),
        ),
    ]
