# Generated by Django 2.1.7 on 2020-11-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0019_auto_20201118_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('simple', '简单'), ('medium', '中等'), ('difficult', '困难')], default='simple', max_length=40, verbose_name='难度'),
        ),
    ]
