# Generated by Django 2.1.7 on 2020-11-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0020_auto_20201118_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='题目来源'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('简单', '简单'), ('中等', '中等'), ('困难', '困难')], default='simple', max_length=40, verbose_name='难度'),
        ),
    ]
