# Generated by Django 2.1.7 on 2020-11-27 06:00

from django.db import migrations, models
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0021_auto_20201119_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=simditor.fields.RichTextField(verbose_name='内容'),
        ),
    ]
