# Generated by Django 2.1.7 on 2020-11-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0022_auto_20201127_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('简单', '简单'), ('中等', '中等'), ('困难', '困难')], default='简单', max_length=40, verbose_name='难度'),
        ),
    ]
