# Generated by Django 2.1.7 on 2020-12-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0023_auto_20201129_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='标题'),
        ),
    ]
